### ISSUE TITLE
Η ακριβής χρήση του Επόμενη σελίδα

### ISSUE THREAD

**Issue by stefanos82** [sfilargi/kurosiwo#1]
Φίλε Σταύρο σε χαιρετώ.

Είδα την ανακοίνωση σου στο Hacker News αλλά δεν βρήκα κάποιο email για να μπορέσω να επικοινωνήσω μαζί σου σε πιο προσωπικό βαθμό για περαιτέρω συζήτηση.

Κοίταξα την σελίδα και μου άρεσε, η αλήθεια να λέγεται. Το πρώτο πράγμα που είδα όμως ήταν την χρήση του κουμπιού "Επόμενη Σελίδα".

Δεν θα ήταν πιο λογικό να εμφανίζεται αυτό το κουμπί αφότου ξεπεράσει τους 50 συνδέσμους η αρχική σελίδα, εξού και το `?skip=50`;

Επίσης διαπίστωσα ότι αφού το πατήσω και με πάρει στην επόμενη ανύπαρκτη σελίδα, το κουμπί εξακολουθεί να λειτουργεί και επιδιώκει να πάει στην επόμενη σελίδα παραλείποντας τους επόμενους 50 συνδέσμους.

Το πιο λογικό σενάριο που σκέφτομαι είναι ένα μετρητή συνδέσμων που θα κάνει την ταύτιση βάσει του αριθμού συνδέσμων που βρίσκονται στην βάση δεδομένων.

Κάτι τελευταίο, τι σημαίνει το kurosiwo ακριβώς; Ελάχιστα Γιαπωνέζικα κατανοώ χάρη στα κινούμενα σχέδια τύπου Naruto και τα λειπά, αλλά τι ακριβώς σημαίνει εσύ βεβαίως γνωρίζεις καλύτερα.

Μπορείς να με διαφωτίσεις;

Να'σαι καλά.

**Comment by sfilargi** [comment]
Γεια σου φίλτατε Στέφανε!

Έχεις απόλυτο δίκιο σχετικά με το functionality του κουμπιού "Επόμενη σελίδα". Σε ευχαριστώ πολύ για την επισήμανση σου. Το διόρθωσα ακριβώς όπως προτείνεις. Είναι ακόμα πολύ νέο το site, οπότε είναι λίγο "rough on the edges". 

Αν δεις οτι ακόμα δεν δουλεύει όπως θα έπρεπε ή κάτι άλλο που στραβό σε παρακαλώ μην διστάσεις να με ενημερώσεις, η ακόμα και να κανείς ένα "pull request" αν επιθυμείς(με μεγάλη χαρά θα σε προσθέσω σαν contributor αν θες).

Σχετικά με το όνομα, είναι παρμένο από το [ποίημα](https://www.sansimera.gr/anthology/316) του Καββαδία, και από οτι λέει το [wikipedia](https://en.wikipedia.org/wiki/Kuroshio_Current), είναι κάτι αντίστοιχο του Gulf Stream.

Το email μού είναι stav@stav.cc, μην διστάσεις να επικοινωνήσεις εκεί για οτιδήποτε!

Σε ευχαριστώ πάλι για το bug report!

**Comment by sfilargi** [comment]
#9c56e1455a997b87b6ce67dfa2f27e5cf212b108
